server:
  port: 9000

spring:
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

logging:
  level:
    hu.martinez.matchsimulator: DEBUG