INSERT INTO team (id, name) VALUES (1, "Arsenal");
INSERT INTO team (id, name) VALUES (2, "Chelsea");
INSERT INTO team (id, name) VALUES (3, "Liverpool");
INSERT INTO team (id, name) VALUES (4, "Manchester City");
INSERT INTO team (id, name) VALUES (5, "Swansea City");
INSERT INTO team (id, name) VALUES (6, "Cardiff City");

-- Arsenal
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Wojciech", "Szczęsny", 1, "pol", 23, "GK", "R", 1, 80, 0, 0);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Emiliano", "Viviano", 1, "ita", 27, "GK", "L", 13, 78, 0, 0);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Łukasz", "Fabiański", 1, "pol", 28, "GK", "R", 21, 75, 0, 0);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Bacary", "Sagna", 1, "fra", 30, "RB", "R", 3, 80, 48, 61);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Carl", "Jenkinson", 1, "eng", 21, "RB", "R", 25, 71, 40, 40);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Héctor", "Bellerín", 1, "esp", 18, "RB", "R", 40, 58, 45, 42);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Per", "Mertesacker", 1, "ger", 28, "CB", "R", 4, 82, 36, 25);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Laurent", "Koscielny", 1, "fra", 28, "CB", "R", 4, 82, 32, 47);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Thomas", "Vermaelen", 1, "bel", 27, "CB", "L", 5, 79, 55, 70);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Kieran", "Gibbs", 1, "eng", 23, "LB", "L", 28, 78, 46, 64);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Nacho", "Monreal", 1, "esp", 27, "LB", "L", 17, 76, 38, 60);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Aaron", "Ramsey", 1, "wal", 22, "CDM", "R", 16, 82, 76, 77);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Mikel", "Arteta", 1, "esp", 31, "CDM", "R", 8, 80, 71, 75);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Mathieu", "Flamini", 1, "fra", 29, "CDM", "R", 20, 79, 57, 70);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Kim", "Källström", 1, "swe", 31, "CDM", "L", 29, 74, 70, 83);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Jack", "Wilshere", 1, "eng", 21, "CM", "L", 10, 82, 64, 73);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Abou", "Diaby", 1, "fra", 27, "CM", "R", 24, 76, 64, 70);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Gedion", "Zelalem", 1, "ger", 16, "CM", "R", 58, 62, 48, 41);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Santi", "Cazorla", 1, "esp", 28, "RM", "R", 19, 84, 77, 82);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Theo", "Walcott", 1, "eng", 24, "RM", "R", 14, 81, 83, 67);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Alex", "Oxlade-Chamberlain", 1, "eng", 20, "RM", "R", 15, 78, 69, 76);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Serge", "Gnabry", 1, "ger", 18, "RM", "R", 44, 70, 57, 58);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Ryo", "Miyaichi", 1, "jap", 20, "RM", "R", 31, 67, 55, 40);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Lukas", "Podolski", 1, "ger", 28, "LM", "L", 9, 77, 87, 85);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Mesut", "Özil", 1, "ger", 24, "CAM", "L", 11, 84, 73, 75);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Tomáš", "Rosický", 1, "cze", 32, "CAM", "R", 7, 81, 65, 70);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Thomas", "Eisfeld", 1, "ger", 20, "CAM", "R", 42, 59, 51, 44);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Olivier", "Giroud", 1, "fra", 26, "ST", "L", 12, 79, 80, 75);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Nicklas", "Bendtner", 1, "den", 25, "ST", "R", 23, 75, 78, 60);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Park", "Chu-Young", 1, "kor", 28, "ST", "R", 30, 68, 67, 68);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Yaya", "Sanogo", 1, "fra", 20, "ST", "R", 22, 68, 68, 50);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Chuba", "Akpom", 1, "eng", 17, "ST", "R", 37, 58, 61, 51);

-- Chelsea
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Petr", "Čech", 2, "cze", 31, "GK", "L", 1, 85, 0, 0);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Mark", "Schwarzer", 2, "aus", 40, "GK", "L", 23, 77, 0, 0);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Henrique", "Hilário", 2, "por", 37, "GK", "L", 40, 70, 0, 0);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Branislav", "Ivanović", 2, "srb", 29, "RB", "R", 2, 81, 56, 61);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("César", "Azpilicueta", 2, "esp", 24, "RB", "R", 28, 79, 46, 60);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("John", "Terry", 2, "eng", 32, "CB", "R", 26, 83, 46, 33);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("David", "Luiz", 2, "bra", 26, "CB", "R", 4, 82, 58, 71);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Gary", "Cahill", 2, "eng", 27, "CB", "R", 24, 80, 60, 66);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Tomáš", "Kalas", 2, "cze", 20, "CB", "R", 33, 74, 37, 64);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Nathan", "Aké", 2, "ned", 18, "CB", "L", 27, 67, 40, 55);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Ashley", "Cole", 2, "eng", 32, "LB", "L", 3, 83, 43, 58);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Ryan", "Bertrand", 2, "eng", 24, "LB", "L", 34, 74, 29, 53);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("", "Ramires", 2, "bra", 26, "CDM", "R", 7, 81, 70, 66);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Nemanja", "Matić", 2, "srb", 25, "CDM", "L", 21, 81, 64, 75);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("John Obi", "Mikel", 2, "nge", 26, "CDM", "R", 12, 79, 44, 59);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Michaël", "Essien", 2, "gha", 30, "CDM", "R", 5, 76, 60, 76);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Frank", "Lampard", 2, "eng", 35, "CM", "R", 8, 80, 82, 85);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Marco", "van Ginkel", 2, "ned", 20, "CM", "R", 16, 76, 72, 70);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("John", "Swift", 2, "eng", 18, "CM", "R", 78, 54, 48, 47);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Juan", "Mata", 2, "esp", 25, "RM", "L", 10, 87, 79, 72);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("", "Willian", 2, "bra", 25, "RM", "R", 22, 83, 75, 80);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Mohamed", "Salah", 2, "egy", 21, "RM", "L", 95, 77, 68, 50);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Eden", "Hazard", 2, "bel", 22, "LM", "R", 17, 88, 83, 82);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("André", "Schürrle", 2, "ger", 22, "LM", "R", 14, 80, 81, 88);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("", "Oscar", 2, "bra", 21, "CAM", "R", 11, 84, 75, 76);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Kevin", "De Bruyne", 2, "bel", 22, "CAM", "R", 15, 81, 78, 83);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Lewis", "Baker", 2, "eng", 18, "CAM", "R", 47, 59, 65, 65);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Fernando", "Torres", 2, "esp", 29, "ST", "R", 9, 82, 81, 78);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Samuel", "Eto'o", 2, "cmr", 32, "ST", "R", 29, 82, 82, 75);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Demba", "Ba", 2, "sen", 28, "ST", "R", 19, 80, 81, 76);

-- Liverpool
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Simon", "Mignolet", 3, "bel", 25, "GK", "R", 22, 82, 0, 0);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Brad", "Jones", 3, "aus", 31, "GK", "L", 1, 71, 0, 0);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Danny", "Ward", 3, "eng", 20, "GK", "R", 52, 57, 0, 0);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Glen", "Johnson", 3, "eng", 29, "RB", "R", 2, 78, 57, 69);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Martin", "Kelly", 3, "eng", 23, "RB", "R", 34, 74, 37, 37);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Andre", "Wisdom", 3, "eng", 20, "RB", "R", 47, 69, 23, 27);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Martin", "Škrtel", 3, "svk", 28, "CB", "R", 37, 81, 35, 35);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Daniel", "Agger", 3, "den", 28, "CB", "L", 5, 81, 58, 73);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Mamadou", "Sakho", 3, "fra", 23, "CB", "L", 17, 81, 23, 38);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Kolo", "Touré", 3, "civ", 32, "CB", "R", 4, 79, 55, 76);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Sebastián", "Coates", 3, "uru", 22, "CB", "R", 16, 71, 22, 26);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("José", "Enrique", 3, "esp", 27, "LB", "L", 3, 79, 42, 53);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Aly", "Cissokho", 3, "fra", 25, "LB", "L", 20, 74, 55, 58);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Jon", "Flanagan", 3, "eng", 20, "LB", "R", 38, 70, 42, 31);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Steven", "Gerrard", 3, "eng", 33, "CDM", "R", 8, 83, 79, 86);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Lucas", "Leiva", 3, "bra", 26, "CDM", "R", 21, 80, 23, 35);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Jordan", "Henderson", 3, "eng", 23, "CM", "R", 14, 78, 64, 68);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Joe", "Allen", 3, "wal", 23, "CM", "R", 24, 77, 57, 59);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Victor", "Moses", 3, "nge", 22, "RM", "R", 12, 75, 69, 67);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Jordon", "Ibe", 3, "eng", 17, "LM", "R", 33, 67, 60, 52);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Philippe", "Coutinho", 3, "bra", 21, "CAM", "R", 10, 81, 66, 68);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("João Carlos", "Teixeira", 3, "por", 20, "CAM", "R", 53, 58, 54, 55);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Daniel", "Sturridge", 3, "eng", 24, "RW", "R", 15, 83, 86, 78);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Raheem", "Sterling", 3, "eng", 18, "LW", "R", 31, 79, 69, 64);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Luis", "Suárez", 3, "uru", 26, "ST", "R", 7, 89, 89, 84);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Iago", "Aspas", 3, "esp", 26, "ST", "L", 9, 76, 78, 73);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Luis", "Alberto", 3, "esp", 20, "ST", "R", 6, 72, 74, 73);

-- Manchester City
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Joe", "Hart", 4, "eng", 26, "GK", "R", 1, 82, 0, 0);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Costel", "Pantilimon", 4, "rou", 26, "GK", "R", 30, 75, 0, 0);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Richard", "Wright", 4, "eng", 35, "GK", "L", 29, 62, 0, 0);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Pablo", "Zabaleta", 4, "arg", 28, "RB", "R", 5, 82, 41, 57);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Micah", "Richards", 4, "eng", 25, "RB", "R", 2, 78, 55, 39);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Vincent", "Kompany", 4, "bel", 27, "CB", "R", 4, 86, 45, 67);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Martín", "Demichelis", 4, "arg", 32, "CB", "R", 26, 79, 43, 34);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Joleon", "Lescott", 4, "eng", 31, "CB", "L", 6, 79, 51, 39);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Matija", "Nastasić", 4, "srb", 22, "CB", "L", 33, 77, 26, 21);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Dedryck", "Boyata", 4, "bel", 22, "CB", "R", 38, 68, 25, 24);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Gaël", "Clichy", 4, "fra", 28, "LB", "L", 22, 80, 33, 42);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Aleksandar", "Kolarov", 4, "srb", 27, "LB", "L", 13, 78, 54, 86);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Gareth", "Barry", 4, "eng", 32, "CDM", "L", 18, 80, 63, 71);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Javi", "García", 4, "esp", 26, "CDM", "R", 14, 79, 59, 73);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("", "Fernandinho", 4, "bra", 28, "CM", "R", 25, 82, 70, 84);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Yaya", "Touré", 4, "civ", 30, "CM", "R", 42, 86, 82, 82);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Jack", "Rodwell", 4, "eng", 22, "CM", "R", 17, 76, 68, 77);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Emir", "Huws", 4, "wal", 19, "CM", "L", 36, 67, 57, 61);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Samir", "Nasri", 4, "fra", 26, "RM", "R", 8, 84, 76, 77);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Jesús", "Navas", 4, "esp", 27, "RM", "R", 15, 83, 67, 74);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("James", "Milner", 4, "eng", 27, "RM", "R", 7, 80, 67, 83);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("David", "Silva", 4, "esp", 27, "LM", "L", 21, 87, 76, 80);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Marcos", "Lopes", 4, "por", 17, "CAM", "L", 64, 65, 60, 52);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Edin", "Džeko", 4, "bih", 27, "ST", "R", 10, 83, 84, 80);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Sergio", "Agüero", 4, "arg", 25, "ST", "R", 16, 88, 90, 79);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Álvaro", "Negredo", 4, "esp", 28, "ST", "L", 9, 83, 84, 78);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Stefan", "Jovetić", 4, "mne", 23, "ST", "R", 35, 83, 82, 80);

-- Swansea City
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Michel", "Vorm", 5, "ned", 29, "GK", "R", 1, 80, 0, 0);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Gerhard", "Tremmel", 5, "ger", 34, "GK", "R", 25, 73, 0, 0);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Gregor", "Zabret", 5, "slo", 18, "GK", "R", 45, 61, 0, 0);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("David", "Cornell", 5, "wal", 22, "GK", "R", 13, 58, 0, 0);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Àngel", "Rangel", 5, "esp", 30, "RB", "R", 22, 76, 55, 58);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Dwight", "Tiendalli", 5, "ned", 27, "RB", "R", 19, 70, 35, 50);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Ashley", "Richards", 5, "wal", 22, "RB", "R", 29, 66, 34, 49);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Ashley", "Williams", 5, "wal", 29, "CB", "R", 6, 79, 36, 39);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Chico", "Flores", 5, "esp", 26, "CB", "R", 4, 77, 20, 52);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Jordi", "Amat", 5, "esp", 21, "CB", "R", 2, 74, 33, 64);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Garry", "Monk", 5, "eng", 34, "CB", "R", 16, 68, 25, 28);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Kyle", "Bartley", 5, "eng", 22, "CB", "R", 5, 65, 23, 25);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Neil", "Taylor", 5, "wal", 24, "LB", "L", 3, 72, 29, 54);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Ben", "Davies", 5, "wal", 20, "LB", "L", 33, 72, 50, 42);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("José", "Cañas", 5, "esp", 26, "CDM", "R", 21, 77, 34, 62);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Leon", "Britton", 5, "eng", 30, "CDM", "R", 7, 75, 54, 47);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Jonjo", "Shelvey", 5, "eng", 21, "CDM", "R", 8, 74, 69, 75);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Nathan", "Dier", 5, "eng", 25, "RM", "R", 12, 74, 76, 73);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Wayne", "Routledge", 5, "eng", 28, "LM", "R", 15, 75, 68, 54);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Roland", "Lamah", 5, "bel", 25, "LM", "L", 14, 73, 57, 64);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Pablo", "Hernández", 5, "esp", 28, "LW", "R", 11, 77, 71, 76);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Jonathan", "De Guzmán", 5, "ned", 25, "CAM", "R", 20, 76, 64, 80);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Alejandro", "Pozuelo", 5, "esp", 21, "CAM", "R", 24, 71, 56, 57);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Jay", "Fulton", 5, "eng", 19, "CAM", "R", 56, 63, 51, 49);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Wilfried", "Bony", 5, "civ", 24, "ST", "R", 10, 81, 82, 80);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("", "Michu", 5, "esp", 27, "ST", "L", 9, 80, 84, 71);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Álvaro", "Vázquez", 5, "esp", 22, "ST", "R", 26, 71, 67, 62);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Marvin", "Emnes", 5, "ned", 25, "ST", "R", 57, 70, 72, 59);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("David", "N'Gog", 5, "fra", 24, "ST", "R", 54, 70, 65, 62);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Leroy", "Lita", 5, "eng", 28, "ST", "R", 18, 67, 69, 52);

-- Cardiff City
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("David", "Marshall", 6, "eng", 1, "GK", "R", 28, 75, 0, 0);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Joe", "Lewis", 6, "eng", 25, "GK", "R", 32, 66, 0, 0);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Simon", "Moore", 6, "eng", 23, "GK", "R", 33, 63, 0, 0);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Kévin", "Théophile-Catherine", 6, "fra", 23, "RB", "R", 28, 72, 38, 47);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Kevin", "McNaughton", 6, "sco", 31, "RB", "R", 25, 69, 49, 44);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Matthew", "Connolly", 6, "eng", 25, "RB", "R", 2, 66, 42, 47);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Steven", "Caulker", 6, "eng", 21, "CB", "R", 4, 76, 31, 22);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("", "Cala", 6, "esp", 23, "CB", "R", 27, 73, 45, 60);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Mark", "Hudson", 6, "eng", 31, "CB", "R", 5, 69, 30, 38);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Ben", "Turner", 6, "eng", 25, "CB", "L", 6, 68, 36, 28);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("", "Fábio", 6, "bra", 23, "LB", "R", 35, 72, 44, 57);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Andrew", "Taylor", 6, "eng", 27, "LB", "L", 3, 66, 31, 39);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Declan", "John", 6, "wal", 18, "LB", "L", 42, 63, 38, 53);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Gary", "Medel", 6, "chi", 26, "CDM", "R", 8, 76, 64, 63);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Peter", "Whittingham", 6, "eng", 28, "CDM", "L", 7, 73, 66, 74);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Aron", "Gunnarsson", 6, "isl", 24, "CDM", "R", 17, 68, 56, 65);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Magnus", "Eikrem", 6, "nor", 23, "CM", "R", 15, 70, 63, 72);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Craig", "Bellamy", 6, "wal", 34, "RM", "R", 39, 74, 73, 72);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Craig", "Noone", 6, "eng", 25, "RM", "L", 16, 72, 62, 66);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Don", "Cowie", 6, "sco", 30, "RM", "R", 19, 67, 59, 67);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Tommy", "Smith", 6, "eng", 33, "RM", "R", 14, 67, 67, 66);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Wilfried", "Zaha", 6, "eng", 20, "LM", "R", 36, 72, 72, 59);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Mats", "Møller Dæhli", 6, "nor", 18, "LM", "R", 29, 68, 52, 51);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Craig", "Conway", 6, "sco", 28, "LM", "R", 22, 69, 66, 62);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Jo", "Inge Berget", 6, "nor", 22, "CAM", "R", 22, 71, 69, 73);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Jordon", "Mutch", 6, "eng", 21, "CAM", "R", 18, 71, 66, 73);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Kim", "Bo-Kyung", 6, "kor", 23, "CAM", "L", 13, 71, 63, 63);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Kenwyne", "Jones", 6, "tri", 28, "ST", "R", 9, 73, 69, 68);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Fraizer", "Campbell", 6, "eng", 25, "ST", "R", 10, 72, 73, 61);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Nicky", "Maynard", 6, "eng", 26, "ST", "R", 23, 71, 71, 74);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Andreas", "Cornelius", 6, "den", 20, "ST", "L", 99, 71, 75, 67);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Joe", "Mason", 6, "irl", 22, "ST", "R", 20, 66, 70, 65);
INSERT INTO player (first_name, last_name, team_id, nationality, age, primary_position, preferred_foot, shirt_number, overall, big_chance_finishing, small_chance_finishing) VALUES ("Rudy", "Gestede", 6, "ben", 24, "ST", "R", 15, 65, 65, 62);

-- loanees
-- ki sung-yeong -> sunderland
-- wilfried zaha -> cardiff
-- kenwyne jones -> cardiff
-- peter odemwingie -> stoke
-- fabio borini -> sunderland
-- victor moses -> liverpool
-- romelu lukaku -> everton